import javax.swing.*;
import java.awt.*;
import java.util.Set;

public class AddRemoveProduct {

    private JLabel productLabel;
    private JLabel descriptionLabel;
    private JLabel amountLabel;
    private JPanel panel1;
    private JTextField productInput;
    private JButton addButton;
    private JButton removeButton;
    private JTextField amountTextField;
    private JTextField descriptionTextField;
    private JLabel productlistLabel;
    private JTextArea productTextArea;
    private JButton searchButton;
    private JFrame frame;

    public AddRemoveProduct() {
        //productTextArea.setColumns(3);
        //productTextArea.setRows(manager.getProductSet().size());
    }

    public JPanel getPanel() {
        return panel1;
    }


    //private void productTextArea() {
    //    Manager manager= new Manager();
    //    productTextArea= new JTextArea(manager.toString());
    //}


    public static void main(String[] args) {
        JFrame frame = new JFrame("AddRemoveProduct");
        frame.setContentPane(new AddRemoveProduct().panel1);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    private void createUIComponents() {

        // TODO: place custom component creation code here
        JFrame frame = new JFrame("Add Remove Manager");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();

        Manager manager = new Manager();
        manager.inputDB();
        Set<Product> products;
        products = manager.getProductSet();
        productTextArea.append(manager.toString());


        panel1.add(productTextArea);
        frame.add(panel1, BorderLayout.CENTER);
        frame.setVisible(true);

    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(6, 5, new Insets(0, 0, 0, 0), -1, -1));
        Font panel1Font = this.$$$getFont$$$("Consolas", Font.PLAIN, 12, panel1.getFont());
        if (panel1Font != null) panel1.setFont(panel1Font);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-7367774)), null));
        productLabel = new JLabel();
        productLabel.setBackground(new Color(-16777216));
        Font productLabelFont = this.$$$getFont$$$("Century Schoolbook", Font.BOLD, 14, productLabel.getFont());
        if (productLabelFont != null) productLabel.setFont(productLabelFont);
        productLabel.setForeground(new Color(-16777216));
        productLabel.setHorizontalAlignment(0);
        productLabel.setHorizontalTextPosition(0);
        productLabel.setText("Product");
        panel1.add(productLabel, new com.intellij.uiDesigner.core.GridConstraints(2, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1, false));
        productInput = new JTextField();
        productInput.setBackground(new Color(-196626));
        panel1.add(productInput, new com.intellij.uiDesigner.core.GridConstraints(2, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        amountTextField = new JTextField();
        panel1.add(amountTextField, new com.intellij.uiDesigner.core.GridConstraints(3, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        amountLabel = new JLabel();
        Font amountLabelFont = this.$$$getFont$$$("Century Schoolbook", Font.BOLD, 14, amountLabel.getFont());
        if (amountLabelFont != null) amountLabel.setFont(amountLabelFont);
        amountLabel.setForeground(new Color(-16777216));
        amountLabel.setHorizontalAlignment(0);
        amountLabel.setHorizontalTextPosition(0);
        amountLabel.setText("Amount");
        panel1.add(amountLabel, new com.intellij.uiDesigner.core.GridConstraints(3, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1, false));
        descriptionTextField = new JTextField();
        descriptionTextField.setBackground(new Color(-196626));
        panel1.add(descriptionTextField, new com.intellij.uiDesigner.core.GridConstraints(4, 2, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
        descriptionLabel = new JLabel();
        descriptionLabel.setBackground(new Color(-11119019));
        Font descriptionLabelFont = this.$$$getFont$$$("Century Schoolbook", Font.BOLD, 14, descriptionLabel.getFont());
        if (descriptionLabelFont != null) descriptionLabel.setFont(descriptionLabelFont);
        descriptionLabel.setForeground(new Color(-16777216));
        descriptionLabel.setHorizontalAlignment(0);
        descriptionLabel.setHorizontalTextPosition(0);
        descriptionLabel.setText("Description");
        panel1.add(descriptionLabel, new com.intellij.uiDesigner.core.GridConstraints(4, 1, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_WEST, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1, false));
        addButton = new JButton();
        addButton.setText("Add");
        panel1.add(addButton, new com.intellij.uiDesigner.core.GridConstraints(5, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, 1, null, null, null, 0, false));
        removeButton = new JButton();
        removeButton.setText("Remove");
        panel1.add(removeButton, new com.intellij.uiDesigner.core.GridConstraints(5, 3, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_VERTICAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 1, false));
        productlistLabel = new JLabel();
        Font productlistLabelFont = this.$$$getFont$$$("Century Schoolbook", Font.BOLD, 14, productlistLabel.getFont());
        if (productlistLabelFont != null) productlistLabel.setFont(productlistLabelFont);
        productlistLabel.setForeground(new Color(-16777216));
        productlistLabel.setHorizontalAlignment(0);
        productlistLabel.setHorizontalTextPosition(0);
        productlistLabel.setText("Product List");
        panel1.add(productlistLabel, new com.intellij.uiDesigner.core.GridConstraints(0, 4, 2, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_NONE, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 1, false));
        productTextArea = new JTextArea();
        Font productTextAreaFont = this.$$$getFont$$$("Consolas", Font.PLAIN, 12, productTextArea.getFont());
        if (productTextAreaFont != null) productTextArea.setFont(productTextAreaFont);
        panel1.add(productTextArea, new com.intellij.uiDesigner.core.GridConstraints(2, 4, 3, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(150, 50), null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    private Font $$$getFont$$$(String fontName, int style, int size, Font currentFont) {
        if (currentFont == null) return null;
        String resultName;
        if (fontName == null) {
            resultName = currentFont.getName();
        } else {
            Font testFont = new Font(fontName, Font.PLAIN, 10);
            if (testFont.canDisplay('a') && testFont.canDisplay('1')) {
                resultName = fontName;
            } else {
                resultName = currentFont.getName();
            }
        }
        return new Font(resultName, style >= 0 ? style : currentFont.getStyle(), size >= 0 ? size : currentFont.getSize());
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }

}
